export const districts = [
  { DistrictId: 1, DistrictName: "Colombo" },
  { DistrictId: 2, DistrictName: "Gampaha" },
  { DistrictId: 3, DistrictName: "Kalutara" },
  { DistrictId: 4, DistrictName: "Kandy" },
  { DistrictId: 5, DistrictName: "Matale" },
  { DistrictId: 6, DistrictName: "Nuwara Eliya" },
  { DistrictId: 7, DistrictName: "Galle" },
  { DistrictId: 8, DistrictName: "Matara" },
  { DistrictId: 9, DistrictName: "Hambantota" },
  { DistrictId: 10, DistrictName: "Jaffna" },
  { DistrictId: 11, DistrictName: "Kilinochchi" },
  { DistrictId: 12, DistrictName: "Mannar" },
  { DistrictId: 13, DistrictName: "Vavuniya" },
  { DistrictId: 14, DistrictName: "Mullaitivu" },
  { DistrictId: 15, DistrictName: "Batticaloa" },
  { DistrictId: 16, DistrictName: "Ampara" },
  { DistrictId: 17, DistrictName: "Trincomalee" },
  { DistrictId: 18, DistrictName: "Kurunegala" },
  { DistrictId: 19, DistrictName: "Puttalam" },
  { DistrictId: 20, DistrictName: "Anuradhapura" },
  { DistrictId: 21, DistrictName: "Polonnaruwa" },
  { DistrictId: 22, DistrictName: "Badulla" },
  { DistrictId: 23, DistrictName: "Moneragala" },
  { DistrictId: 24, DistrictName: "Ratnapura" },
  { DistrictId: 25, DistrictName: "Kegalle" },
];
